#!/usr/bin/env python
from random import randint
from time import sleep
import metartg
import sys

logfile = file('/var/log/metartg.log', 'a')
sys.stdout = logfile
sys.stderr = logfile

sleep(randint(1, 25))
metartg.run_checks(sys.argv[1:])
