#!/usr/bin/env python
import metartg
import optparse
import sys

parser = optparse.OptionParser(usage='%prog [options] <checks>')
parser.add_option('-d', '--debug', dest='debug', default=False,
                  action='store_true',
                  help='Print the JSON metrics that would be sent to the ' + \
                       'metartg server')
options, args = parser.parse_args()

if options.debug:
    import simplejson as json
    results = {}
    def callback(service, metrics):
        if not service in results:
            results[service] = []
        results[service].append(metrics)

    for checkname, check in metartg.get_checks(args):
        print checkname
        check.run_check(callback)
        print json.dumps(results, indent=2, sort_keys=True, use_decimal=True)
        results = {}
else:
    logfile = file('/var/log/metartg.log', 'a')
    sys.stdout = logfile
    sys.stderr = logfile

    metartg.run_checks(args)
